#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
SNAPADV = snap-adv

HDF5LIB=/usr/lib/x86_64-linux-gnu/hdf5/serial
HDF5=/usr/include/hdf5/serial

CGLIB = ../$(GLIB)
CSNAP = ../$(SNAP)

EXGLIB = ../../$(GLIB)
EXSNAP = ../../$(SNAP)
EXSNAPADV = ../../$(SNAPADV)

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  CXXFLAGS = -std=gnu++17 -Wall
  CXXFLAGS += -O3 -DNDEBUG -fopenmp
  CXXOPENMP = 
  LDFLAGS +=
  LIBS += -lrt

else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = g++
  CXXFLAGS += -std=gnu++17 -Wall -Wno-unknown-pragmas # -Wextra -Wpedantic
  CXXFLAGS += -O3 -DNDEBUG -pthread
  CLANG := $(shell g++ -v 2>&1 | grep clang | cut -d " " -f 2)
  ifneq ($(CLANG), LLVM)
    # CXXFLAGS += -fopenmp
    CXXFLAGS += -Xpreprocessor -fopenmp -lomp
    #CXXOPENMP += -fopenmp
  else
    CXXFLAGS += -Xpreprocessor -fopenmp -lomp
    #CXXOPENMP =
  endif
  LDFLAGS +=
  LIBS += -lemon
else ifeq ($(shell uname -o), Cygwin)
  CC = g++
  CXXFLAGS += -std=gnu++17 -Wall -D__STDC_LIMIT_MACROS
  CXXFLAGS += -O3 -DNDEBUG
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS +=

endif

